export enum EMPLOYEE_ROLES_UPPERCASE {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_HR = 'ROLE_HR',
  ROLE_EMPLOYEE = 'ROLE_EMPLOYEE',
}

export enum EMPLOYEE_POSITIONS_UPPERCASE {
  QA = 'QA',
  FULLSTACK_DEVELOPER = 'FULLSTACK_DEVELOPER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  HR_MANAGER = 'HR_MANAGER',
  OFFICE_MANAGER = 'OFFICE_MANAGER',
  RECRUITER = 'RECRUITER',
  JAVA_DEVELOPER = 'JAVA_DEVELOPER',
  REACT_DEVELOPER = 'REACT_DEVELOPER',
  NODE_DEVELOPER = 'NODE_DEVELOPER',
  DESIGNER = 'DESIGNER',
}
