export const COLORS = {
  baseLightColor: '#25BAD1',
  baseLightHoverColor: '#26ADC1',
  baseDarkColor: '#173F53',
  baseDarkTransparentColor: '#9AB1BC',
  backgroundColor: '#F9F9FD',
  basePlaceholderColor: '#9AB1BC',
  greenIcon: '#7BDFC7',
  greenLightBG: '#C8F0E6',
  orangeIcon: '#FFC98A',
  orangeLightBG: '#FAE6D2',
  redIcon: '#F7867E',
  redLightBG: '#FAC8C8',
  blueIcon: '#7AB2FD',
  blueLightBG: '#C8E1FA',
  greyBlueIcon: '#9FA8C0',
  disabledBtn: '#D1DBE0',
  baseGreyBackground: '#F7F8F9',
  baseLightGreyBackground: '#FBFCFD',
  baseBorderGreyBackground: '#F6F8F9',
  greyImgBG: '#F3F5F7',
  lightGreyBlueBG: '#EFEFF6',
  baseIcon: '#EFEFF6',
  materialGreyBorder: '#E0E0E0',
  darkBtnColor: '#F6F7FA',
};
